### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by pinksynth** [danielberkompas/ex_twilio#126]
Hello, is there any existing support (or plan to support) having multiple accounts for one application? I am building an app which uses two separate sets of credentials for Programmable SMS—some features are in a staging environment and should be using our Test SID / Test Auth Token.

Thanks for all your work on this package, it has made integrating with Twilio a breeze!

**Comment by atonse** [comment]
I came here in search for this and after looking at the code, it looks like you can just pass in a custom `account:` and `token:` into your API call and it'll pick that up.

For example: `ExTwilio.Message.create(account: account_sid, token: token)`

This has worked well for us, since we have a multi-tenant system and each customer can have a separate twilio account.

**Comment by danielberkompas** [comment]
@atonse has the correct solution for now. In the future, we could revisit this.
