### ISSUE TITLE
Migrate to Jason

### ISSUE THREAD

**Issue by derekbrown** [danielberkompas/ex_twilio#137]
I know that Jason was recently removed from this library in favor of Poison, but has there been any discussion around moving to Jason vs. Poison?

The larger Elixir community seems to have decided on Jason (namely the Phoenix library moving to Jason) as the parser of choice. 

I'm currently using ex_twilio in production (thanks, btw!) and it's the only consumer of Poison for me. If the community doesn't want to move to Jason, could the parser be made configurable?

**Comment by danielberkompas** [comment]
@derekbrown ExTwilio still uses Poison because it makes heavy use of Poison's `decode(string, as: struct)` feature, which to my knowledge, Jason doesn't implement. I'd happily accept pull requests to make the library configurable, but it would require bringing some version of this feature into this library's code on top of the parser.

https://github.com/danielberkompas/ex_twilio/blob/ee4b61149cb052b1cc5a96353c5c16b98cc13f8a/lib/ex_twilio/parser.ex#L87

**Comment by tomciopp** [comment]
See #143

**Comment by doughsay** [comment]
The switch to Jason happened in November of last year.  Can we get a new release that includes this switch please?  Thanks!

**Comment by danielberkompas** [comment]
@doughsay done! I released v0.9.0 just now.
