### ISSUE TITLE
problem with AvailablePhoneNumbers.all

### ISSUE THREAD

**Issue by techgaun** [danielberkompas/ex_twilio#96]
This is the error I get with `ExTwilio.AvailablePhoneNumber.all()`

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/stream.ex:1411: Stream.do_enum_resource/6
    (elixir) lib/enum.ex:1919: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
    (elixir) lib/enum.ex:1163: Enum.into/2
    (ex_twilio) lib/ex_twilio/resources/available_phone_number.ex:20: ExTwilio.AvailablePhoneNumber.all/1
```

The problem seems to be because of the way `ExTwilio` is expecting the body to be. The response body has the following structure:

```
{
	"uri": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers.json",
	"countries": [{
		"country_code": "IL",
		"country": "Israel",
		"uri": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/IL.json",
		"beta": false,
		"subresource_uris": {
			"local": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/IL/Local.json",
			"toll_free": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/IL/TollFree.json",
			"mobile": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/IL/Mobile.json"
		}
	}, {
		"country_code": "US",
		"country": "United States",
		"uri": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/US.json",
		"beta": false,
		"subresource_uris": {
			"local": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/US/Local.json",
			"toll_free": "/2010-04-01/Accounts/AC6fc00e901b08cf09d865ba437f8ae0d1/AvailablePhoneNumbers/US/TollFree.json"
		}
	}]
}
```

Looks like the implementation would try to look at *available_phone_numbers* key under the response but the result does not have that.

Also, I am not sure how we would go about fixing this esp. it would be probably good to generate `ExTwilio.AvailablePhoneNumbers.US.all()` and so

**Comment by john-griffin** [comment]
Also just hit this

**Comment by photomattmills** [comment]
Should you find yourself hitting this issue, and you don't really need to have a specific number, you can use `IncomingPhoneNumber.create/2` and supply an `area_code`, like so: 

```elixir
ExTwilio.IncomingPhoneNumber.create(area_code: "415")
```

(I just spent far too long figuring that out, so I figured I'd save someone else the time).

**Comment by LWCoder** [comment]
When running `ExTwilio.AvailablePhoneNumber.all()` the error referenced in the original issue above still occurs. @mjaric is correct that this is because the returned data from Twilio isn't what ex_twilio expects as it is a list of countries and types of phone numbers (Local, Mobile, Tollfree) instead of the numbers themselves.

I still can't find this documented anywhere, but after digging into the code I found that the UrlGenerator does understand the country and type specific requests that the AvailablePhoneNumber endpoint returns.

The only way to make the `.all()` function work is to provide the two correct options, even though none are explicitly required. More options can be added to filter the results, but the first two must always be provided.

For example:

```elixir
    # US Local Numbers
    ExTwilio.AvailablePhoneNumber.all(iso_country_code: "US", type: "Local")

    # US Local Numbers for an area code
    ExTwilio.AvailablePhoneNumber.all(iso_country_code: "US", type: "Local", area_code: "321")
```
